plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'net.chronoshield.iaapp'
    compileSdk 34

    defaultConfig {
        applicationId "net.chronoshield.iaapp"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "0.2.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.core:core-ktx:1.12.0'
    // Motor de IA local (on-device), sin servidor, sin nube:
    implementation 'com.google.mediapipe:tasks-genai:0.10.14'
}
